name: DHB
description: A new Flutter project.

publish_to: 'none' # Remove this if you plan to publish the package

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  mappls_gl: ^1.2.0
  http: ^1.4.0
  flutter_local_notifications: ^19.2.1
  image_picker: ^1.1.2
  flutter_osm_plugin: ^1.3.8
  flutter_overpass: ^1.2.0
  geolocator: ^14.0.1
  google_maps_flutter: ^2.6.0 # This needs to be updated to a compatible version with your Flutter SDK
  fl_chart: ^1.0.0
  qr_flutter: ^4.0.0
  maplibre_gl: ^0.22.0
  speech_to_text: ^7.0.0 # Updated version
  flutter_tts: ^4.2.3
  audioplayers: ^6.5.0
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.3.0
  flutter_dotenv: ^5.1.0
  validatorless: ^1.2.4



  # google_maps_webservice: ^0.0.20



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/bg.png
